In [ ]:
# Matrizes : São vetores multidimensionais

import numpy as np

In [4]:
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]]) 
# Temos que uma lista aninhada (varias listas dentro de uma lista)
# passada para um array vira uma Matriz

In [5]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
type(matriz)

numpy.ndarray

In [7]:
matriz2 = np.matrix([[1,2,3],[4,5,6],[7,8,9]]) # Outra forma de criar a Matriz

In [8]:
matriz2

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [10]:
type(matriz2)

numpy.matrix

In [11]:
matriz2[1,1] # O primeiro indice é de linha o segundo de coluna

5

In [14]:
matriz2[2,0]

7

In [15]:
matriz2[:,2] # Pegou toda a columa de indice 2 (3 coluna, index começa em 0)

matrix([[3],
        [6],
        [9]])

In [16]:
matriz2[1,:] # Pegou toda a linha de indice 1 (linha 2, index começa em 0)

matrix([[4, 5, 6]])